name: Lint CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Install dependencies
      uses: mstksg/get-package@master
      with:
        apt-get: libgpgme-dev libbtrfs-dev libdevmapper-dev

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      env:
        PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig/
      with:
        version: v1.29
        args: --timeout=3m12s
        skip-go-installation: true
